//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TailspinFunctionalTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TailspinResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TailspinResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TailspinFunctionalTests.Properties.TailspinResource", typeof(TailspinResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /survey/adatum.
        /// </summary>
        public static string adatum {
            get {
                return ResourceManager.GetString("adatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question.
        /// </summary>
        public static string addQuestionLink {
            get {
                return ResourceManager.GetString("addQuestionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addToSurvey.
        /// </summary>
        public static string addToSurveyButton {
            get {
                return ResourceManager.GetString("addToSurveyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to analyze.
        /// </summary>
        public static string analyze {
            get {
                return ResourceManager.GetString("analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answer1.
        /// </summary>
        public static string answer1 {
            get {
                return ResourceManager.GetString("answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answer2.
        /// </summary>
        public static string answer2 {
            get {
                return ResourceManager.GetString("answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answer3.
        /// </summary>
        public static string answer3 {
            get {
                return ResourceManager.GetString("answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answer4.
        /// </summary>
        public static string answer4 {
            get {
                return ResourceManager.GetString("answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentModel_PossibleAnswers.
        /// </summary>
        public static string answerMultippleChoiceFinish {
            get {
                return ResourceManager.GetString("answerMultippleChoiceFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentModel_QuestionAnswers_0__Answer.
        /// </summary>
        public static string answerSimpleTextFinish {
            get {
                return ResourceManager.GetString("answerSimpleTextFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentModel_PossibleAnswers.
        /// </summary>
        public static string answerTextArea {
            get {
                return ResourceManager.GetString("answerTextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to Tailspin.
        /// </summary>
        public static string backToTailspinText {
            get {
                return ResourceManager.GetString("backToTailspinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://127.0.0.1:444.
        /// </summary>
        public static string baseUrl {
            get {
                return ResourceManager.GetString("baseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string cancelLink {
            get {
                return ResourceManager.GetString("cancelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentPlaceholder_ContinueButton.
        /// </summary>
        public static string continueButton {
            get {
                return ResourceManager.GetString("continueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create.
        /// </summary>
        public static string createButton {
            get {
                return ResourceManager.GetString("createButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        public static string current {
            get {
                return ResourceManager.GetString("current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onclick=javascript: submitToDelete(&apos;/survey/adatum/.
        /// </summary>
        public static string deleteLink1 {
            get {
                return ResourceManager.GetString("deleteLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /delete&apos;).
        /// </summary>
        public static string deleteLink2 {
            get {
                return ResourceManager.GetString("deleteLink2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onclick=javascript: submitToDelete(&apos;/survey/fabrikam/.
        /// </summary>
        public static string deleteLinkFabrikam {
            get {
                return ResourceManager.GetString("deleteLinkFabrikam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#13;.
        /// </summary>
        public static string enterCheck {
            get {
                return ResourceManager.GetString("enterCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /survey/fabrikam.
        /// </summary>
        public static string fabrikam {
            get {
                return ResourceManager.GetString("fabrikam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finish.
        /// </summary>
        public static string finishButton {
            get {
                return ResourceManager.GetString("finishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for filling the survey!.
        /// </summary>
        public static string finishsurveyText {
            get {
                return ResourceManager.GetString("finishsurveyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string forwardSlash {
            get {
                return ResourceManager.GetString("forwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to href=.
        /// </summary>
        public static string href {
            get {
                return ResourceManager.GetString("href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerText=.
        /// </summary>
        public static string innerText {
            get {
                return ResourceManager.GetString("innerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADATUM\johndoe.
        /// </summary>
        public static string johnDoe {
            get {
                return ResourceManager.GetString("johnDoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentPlaceholder_UserList_0.
        /// </summary>
        public static string loginJohndoe {
            get {
                return ResourceManager.GetString("loginJohndoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * You must provide an answer..
        /// </summary>
        public static string mandatoryAnswer {
            get {
                return ResourceManager.GetString("mandatoryAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Answers must be supplied for the question..
        /// </summary>
        public static string mandatoryAnswerMultipleChoice {
            get {
                return ResourceManager.GetString("mandatoryAnswerMultipleChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * You must provide a Question..
        /// </summary>
        public static string mandatoryQuestion {
            get {
                return ResourceManager.GetString("mandatoryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * You must provide a Title for the survey..
        /// </summary>
        public static string mandatoryTitle {
            get {
                return ResourceManager.GetString("mandatoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabrikam\mary.
        /// </summary>
        public static string mary {
            get {
                return ResourceManager.GetString("mary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string myAccount {
            get {
                return ResourceManager.GetString("myAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survey/adatum.
        /// </summary>
        public static string mySurveyLink {
            get {
                return ResourceManager.GetString("mySurveyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survey/fabrikam.
        /// </summary>
        public static string mySurveyLinkFabrikam {
            get {
                return ResourceManager.GetString("mySurveyLinkFabrikam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Surveys.
        /// </summary>
        public static string mySurveys {
            get {
                return ResourceManager.GetString("mySurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newquestion.
        /// </summary>
        public static string newQuestion {
            get {
                return ResourceManager.GetString("newQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Survey.
        /// </summary>
        public static string newSurvey {
            get {
                return ResourceManager.GetString("newSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survey/adatum/newsurvey.
        /// </summary>
        public static string newsurveyUrl {
            get {
                return ResourceManager.GetString("newsurveyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survey/fabrikam/newsurvey.
        /// </summary>
        public static string newsurveyUrlFabrikam {
            get {
                return ResourceManager.GetString("newsurveyUrlFabrikam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no surveys..
        /// </summary>
        public static string noSurveys {
            get {
                return ResourceManager.GetString("noSurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overridelink.
        /// </summary>
        public static string overridelink {
            get {
                return ResourceManager.GetString("overridelink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to question1.
        /// </summary>
        public static string question1 {
            get {
                return ResourceManager.GetString("question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentModel_Text.
        /// </summary>
        public static string questionText {
            get {
                return ResourceManager.GetString("questionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiplechoice.
        /// </summary>
        public static string quesTypeMultipleChoice {
            get {
                return ResourceManager.GetString("quesTypeMultipleChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fivestars.
        /// </summary>
        public static string quesTypeRating {
            get {
                return ResourceManager.GetString("quesTypeRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to simpletext.
        /// </summary>
        public static string quesTypeSimpleText {
            get {
                return ResourceManager.GetString("quesTypeSimpleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentModel_Type.
        /// </summary>
        public static string selectQuestionType {
            get {
                return ResourceManager.GetString("selectQuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signout.
        /// </summary>
        public static string signout {
            get {
                return ResourceManager.GetString("signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adatum issuer.
        /// </summary>
        public static string simulatedIssuerPageTitle {
            get {
                return ResourceManager.GetString("simulatedIssuerPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabrikam issuer.
        /// </summary>
        public static string simulatedIssuerPageTitleFabrikam {
            get {
                return ResourceManager.GetString("simulatedIssuerPageTitleFabrikam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost/Adatum.SimulatedIssuer.v2/SimulatedWindowsAuthentication.aspx.
        /// </summary>
        public static string simulatedIssuerUrl {
            get {
                return ResourceManager.GetString("simulatedIssuerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost/Fabrikam.SimulatedIssuer.v2/SimulatedWindowsAuthentication.aspx.
        /// </summary>
        public static string simulatedIssuerUrlFabrikam {
            get {
                return ResourceManager.GetString("simulatedIssuerUrlFabrikam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string star1 {
            get {
                return ResourceManager.GetString("star1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string star2 {
            get {
                return ResourceManager.GetString("star2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string star3 {
            get {
                return ResourceManager.GetString("star3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string star4 {
            get {
                return ResourceManager.GetString("star4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string star5 {
            get {
                return ResourceManager.GetString("star5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;.
        /// </summary>
        public static string surveyAlreadyPresent1 {
            get {
                return ResourceManager.GetString("surveyAlreadyPresent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; is already in use. Please choose another name..
        /// </summary>
        public static string surveyAlreadyPresent2 {
            get {
                return ResourceManager.GetString("surveyAlreadyPresent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagname=a.
        /// </summary>
        public static string tagnameA {
            get {
                return ResourceManager.GetString("tagnameA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagname=H1.
        /// </summary>
        public static string tagNameH1 {
            get {
                return ResourceManager.GetString("tagNameH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagname=H2.
        /// </summary>
        public static string tagNameH2 {
            get {
                return ResourceManager.GetString("tagNameH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagname=H3.
        /// </summary>
        public static string tagNameH3 {
            get {
                return ResourceManager.GetString("tagNameH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagname=li.
        /// </summary>
        public static string tagnameListItem {
            get {
                return ResourceManager.GetString("tagnameListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagname=span.
        /// </summary>
        public static string tagnameSpan {
            get {
                return ResourceManager.GetString("tagnameSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagname=strong.
        /// </summary>
        public static string tagnameStrong {
            get {
                return ResourceManager.GetString("tagnameStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagname=TD.
        /// </summary>
        public static string tagnameTD {
            get {
                return ResourceManager.GetString("tagnameTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailspin - On boarding.
        /// </summary>
        public static string tailSpinPageTitle {
            get {
                return ResourceManager.GetString("tailSpinPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost/Tailspin.SimulatedIssuer.
        /// </summary>
        public static string tailSpinSimulatedIssuerUrl {
            get {
                return ResourceManager.GetString("tailSpinSimulatedIssuerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to textcontent=.
        /// </summary>
        public static string textcontent {
            get {
                return ResourceManager.GetString("textcontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thankyou.
        /// </summary>
        public static string thankyou {
            get {
                return ResourceManager.GetString("thankyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentModel_Title.
        /// </summary>
        public static string titleText {
            get {
                return ResourceManager.GetString("titleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value=.
        /// </summary>
        public static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
    }
}
